name: coride_app
description: Application de covoiturage CoRide en Tunisie
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Backend)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10

  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

  # Navigation
  go_router: ^13.0.0

  # State Management
  provider: ^6.1.1

  # Géolocalisation
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3

  # Date & Time
  intl: ^0.19.0

  # Utilitaires
  url_launcher: ^6.2.3
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  permission_handler: ^11.2.0
  uuid: ^4.3.3
  timeago: ^3.6.0
  flutter_rating_bar: ^4.0.1
  pinput: ^3.0.1

  # Icônes
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration Assets
flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/
    - assets/images/logo.png
    - assets/images/CoRide.png
    - assets/images/widget.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/widget.png"